#:schema https://json.schemastore.org/ruff.json

builtins = ["ic"]
fix = true
show-fixes = true
target-version = "py312"

[format]
docstring-code-format = true

[lint]
explicit-preview-rules = true
ignore = ["ANN401", "COM812", "D100", "D104", "E501", "S101", "S603"]
preview = true
select = ["ALL", "RUF022"]

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.pydocstyle]
convention = "google"
