name: CI

on:
  push:
  release:
    types:
      - published

env:
  UV_INDEX_URL: https://pypi.org/simple

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Install Dependencies
        run: |-
          uv sync --all-extras
          uv build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - if: ${{ github.event_name == 'release' }}
        name: Upload Release Assets
        uses: liblaf/actions/release@main
        with:
          clobber: false
          files: |-
            dist/*.tar.gz
            dist/*.whl
          prerelease: false
          tag: ${{ github.event.release.tag_name }}
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Upload Release Assets
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: |-
            dist/*.tar.gz
            dist/*.whl
          prerelease: true
          tag: latest
