name: CI

on:
  push:

jobs:
  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v3
      - name: Install Dependencies
        run: |-
          uv sync --all-extras
          uv build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
      - name: Create Pre-Release
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: |-
            dist/*.tar.gz
            dist/*.whl
          prerelease: true
          tag: latest

  release-please:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/.manifest.json

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.created == 'true' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/
      - name: Upload Release Assets
        uses: liblaf/actions/release@main
        with:
          clobber: true
          files: dist/*
          tag: ${{ needs.release-please.outputs.tag-name }}
